name: fake-news-detection
channels:
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - nltk
      - matplotlib
      - seaborn
      - jupyterlab
      - ipykernel
      - tqdm
      - tensorflow
      - keras
      - datasets
      - ipywidgets
      - Unidecode
      - transformers
      - openai
      - python-dotenv
      - openpyxl
      - gdown
      - nlpaug
      - PyYAML
