datasets_root: "../datasets"

preprocessing:
  lowercase: true
  remove_punctuation: true
  remove_urls: true
  remove_digits: true
  strip_html: true
  remove_special_chars: true
  normalize_whitespace: true

augmentation:
  synonym_replacement:
    enabled: false
    n_samples: 0.01
  style_transfer:
    enabled: false
    n_samples: 0.01
  paraphrasing:
    enabled: false
    n_samples: 0.01
  
augmentation_methods:
  local_database: false
  llm: true
 
tokenization:
  tokenizer_model: "bert-base-uncased"
  sequence_max_length: 256


output:
  processed_data_dir: "output"
  model_save_dir: "models"